logging:
    level:
        org.springframework: INFO

        nl.hoepsch: DEBUG

    pattern:
        console: "%white(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) [%blue(%X{tx.id}) %white(%X{task.id})] %white([%thread]) %cyan(%logger:%line) - %msg%n"

spring:
    kafka:
        bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
        schema:
            registry:
                url: http://localhost:19091
                initial-capacity: 100
        topic:
            requestreply-topic: "shopping-cart-external-validation"
